title: Cesar's Ramirez CIT_481 Blog 4_2022

logo: /assets/img/azure_or_aws.png
description: A blog for Technology and tools for the CIT comunity
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
